version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.20
  pre_build:
    commands:
      - echo git clone .....
      - git version
      - git clone https://github.com/cyt1999/kube-prometheus.git
  build:
    commands:
      - echo Build started on `date`
      - go env
  post_build:
    commands:
      - echo Build completed on `date`
