version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.20
  pre_build:
    commands:
      - echo git clone .....
      - git version
  build:
    commands:
      - echo Build started on `date`
      - go env
  post_build:
    commands:
      - echo Build completed on `date`
