name: Build and Deploy 

on: 
  workflow_dispatch:
    inputs:
      token:
        description: 'token'
        default: 'latest'
        required: true
        type: string
      repositories:
        description: 'repositories'
        default: 'https://github.com/cyt1999/kube-prometheus.git'
        required: true
        type: string
      tag:
        description: 'tag'
        default: 'latest'
        required: true
        type: string

  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    
    - id: clone_repository
      name: Fetch dependent repository  
      run: |  
        echo ${{ inputs.repositories }}
        git clone ${{ inputs.repositories }}
        # 对拉取的模板库重命名 
        # mv png_nft_generator png_nft_csv_template     

    # - id: install_rust
    #   name: Install Rust
    #   # uses: dtolnay/rust-toolchain@stable
    #   uses: dtolnay/rust-toolchain@1.42.0
      
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true

    - id: check
      name: check template repository
      run: |
        echo "cargo build --target wasm32-wasi"
        rustup -V
        cargo version
        
    - id: build
      name: Install and Build
      run: |
        echo "cargo build --target wasm32-wasi"
        rustup -V
        cargo version

    #状态检查
    
    - name: The job has succeeded
      if: ${{ success() }}
      run: |
        echo "success"
        
    - name: The clone repository has failed
      if: ${{ failure() && steps.clone_repository.conclusion == 'failure' }}
      run: |
        echo "Fetch dependent repository  "

    - name: The build has failed
      if: ${{ failure() && steps.build.conclusion == 'failure' }}
      run: |
          echo "Install and Build"


