name: GitHub Actions Build and Deploy Demo

on: 
  workflow_dispatch:
    inputs:
      repositories:
        description: '用户模板仓库地址'
        default: 'https://github.com/cyt1999/kube-prometheus.git'
        required: true
        type: string

env:
  REPOSITORIES_URL: test
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - id: checkout
      uses: actions/checkout@v4 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
      # with:
      #   persist-credentials: false
    
    - name: Fetch dependent repository  
      id: clone_repository
      run: |  
        echo ${{ inputs.repositories }}
        git clone ${{ inputs.repositories }}
        # 如果需要，您可以将克隆的仓库移动到适当的目录  
        # mv png_nft_generator /path/to/destination
        echo 状态 ${{ steps.clone_repository.outcome }}
        echo 状态 ${{ steps.clone_repository.conclusion }}
        echo ${{ steps }}
        

    - id: install_rust
      name: Install Rust
      # uses: dtolnay/rust-toolchain@stable
      uses: dtolnay/rust-toolchain@1.42.0
      
    - id: build
      name: Install and Build
      run: |
        ls 
        pwd
        echo "cargo build --target wasm32-wasi"
        rustup -V
        cargo version


